# -*- coding: utf-8 -*-
"""thuc-hanh-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIFrptfJA_Z2RDb6QfwWWKjszZAGOBjn

THỰC HÀNH THỐNG KÊ MÔ TẢ VỚI DỮ LIỆU ĐỊNH LƯỢNG

Sử dụng tập dữ liệu microbiome.csv được cung cấp để hoàn thành các bài tập sau
"""

import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

"""Câu 1: Tải tập dữ liệu microbiome.csv vào bộ nhớ (sử dụng pandas)"""

df = pd.read_csv("microbiome.csv")
df

"""NHÓM CÁC CÂU LỆNH THỰC HIỆN CÁC PHÉP TÍNH HƯỚNG TÂM

Câu 2: Hãy tính trung bình cộng của cột Patient
"""

#Code
df["Patient"].mean()

"""Câu 3: Hãy tính trung bình cộng (mean) đồng thời cho 3 cột Patient, Tissue và Stool"""

#Code
df.mean()

"""Câu 4: Hãy tính trung vị (median) cho 2 cột Tissue và Stool"""

#Code
df[["Tissue", "Stool"]].median()

"""Câu 5: Hãy tính số yếu vị (mode) cho 3 cột Patient, Tissue và Stool"""

#Code
df[["Tissue", "Stool", "Patient"]].mode()

"""NHÓM CÂU LỆNH TÍNH PHƯƠNG SAI - ĐỘ LỆCH CHUẨN

Câu 6: Hãy tính phương sai (variance) của cột Tissue
"""

#Code
df["Tissue"].var()

"""Câu 7: Hãy tính phương sai của 3 cột Patient, Tissue và Stool"""

#Code
df.var()

"""Câu 8: Hãy tính độ lệch chuẩn (standard deviation) của 3 cột Patient, Tissue và Stool"""

#Code
df.std()

"""NHÓM CÂU LỆNH TÍNH PHÂN VỊ (PERCENTILE)

Câu 9: Tính Q1 Q2 và Q3 cho cột Tissue

Tham khảo:

1) https://www.geeksforgeeks.org/python-pandas-dataframe-quantile/

2) https://stackoverflow.com/questions/45926230/how-to-calculate-1st-and-3rd-quartiles/45926291
"""

#Code
df.Tissue.quantile([0.25,0.5,0.75])

"""Câu 10: Hãy tính z-score cho cột Tissue

Gợi ý: sử dụng hàm zscore của thư viện scipy

Tham khảo: https://stackoverflow.com/questions/24761998/pandas-compute-z-score-for-all-columns
"""

#Code
stats.zscore(df["Tissue"])

"""NHÓM CÂU LỆNH TỔNG HỢP

Câu 11: (bổ sung) Hãy tính giá trị lớn nhất và nhỏ nhất của 3 cột Patient, Tissue và Stool
"""

#Code
print("GTLN Tissue, Patient, Stool lần lượt là: ", max(df["Tissue"]), max(df["Patient"]), max(df["Stool"]))
print("GTNN Tissue, Patient, Stool lần lượt là: ", min(df["Tissue"]), min(df["Patient"]), min(df["Stool"]))

"""Câu 12: Hãy thực thi hàm describe đối với data frame chứa dữ liệu của microbiome.csv

Tham khảo: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html
"""

#Code
df.describe()

"""NHÓM CÂU LỆNH ĐỒ HỌA

Câu 13: Hãy vẽ biểu đồ box plot cho cột Tissue
"""

#Code
plt.boxplot(df["Tissue"])
plt.show()

"""Câu 14: Hãy vẽ biểu đồ box plot cho cả 2 cột Tissue và Stool chung 1 hình (gồm có 2 box plot)"""

#Code
df[["Tissue", "Stool"]].boxplot()
plt.show()

"""Câu 15: Hãy vẽ lại câu 14 với các box plot nằm ngang"""

#Code

#Code
df[["Tissue", "Stool"]].boxplot(vert=False)
plt.show()

"""Câu 16: Hãy sử dụng thư viện seaborn để vẽ biểu đồ box plot cho Tissue và Stool"""

#Code
sns.boxplot(data = df[["Tissue","Stool"]])
plt.show()